tap "azure/bicep", trusted: true
tap "azure/functions", trusted: true
tap "fluxcd/tap", trusted: true
# mockpy's tap: oarrabi/tap now redirects here. It ships a broken "codeimager"
# cask (header token does not match the file name), so `brew tap` fails its audit
# on a fresh machine; the clone still lands, so a second run succeeds.
tap "nsomar/tap", trusted: true
tap "run-llama/liteparse", trusted: true
brew "act"
brew "actionlint"
brew "age"
brew "tree"
brew "ansible"
brew "ansible-lint"
brew "azure-cli"
brew "bash"
brew "btop"
brew "exiftool"
brew "fd"
brew "flock"
brew "fzf"
brew "gcc"
brew "gh"
brew "git-filter-repo"
brew "libusb"
brew "gnupg"
brew "go"
brew "go-task"
brew "gradle"
brew "librsvg"
brew "graphviz"
brew "helm"
brew "jq"
brew "lazygit"
brew "maven"
brew "mise"
brew "neovim"
brew "net-snmp"
brew "nmap"
brew "node"
brew "nvm"
brew "opentofu"
brew "pinentry-mac"
brew "pipx"
brew "rbw"
brew "rclone"
brew "ripgrep"
# terraform is no longer in homebrew-core (BUSL relicense); opentofu covers it.
# terraformer: upstream repo is archived, Homebrew disables it on 2027-06-08.
brew "terraformer"
brew "uv"
brew "watch"
brew "watchman"
brew "wget"
brew "yq"
brew "zbctl"
brew "azure/bicep/bicep"
brew "azure/functions/azure-functions-core-tools@4"
brew "fluxcd/tap/flux"
brew "nsomar/tap/mockpy"
brew "run-llama/liteparse/llamaindex-liteparse"
brew "arp-scan"
brew "mactop"
brew "mosquitto"
brew "prometheus"
brew "yamllint"
brew "imagemagick"
brew "marp-cli"
brew "php"
brew "poppler"
brew "wp-cli"
brew "ghostscript"
brew "pandoc"
brew "weasyprint", link: false
brew "e2fsprogs"
brew "ffmpeg"
brew "sshpass"
brew "typst"
brew "unar"
# Dropped casks and why:
#   chromium        — disabled by Homebrew 2026-09-01 (fails macOS Gatekeeper)
#   mullvad-browser — download blocked by the corporate proxy (403)
#   vnc-viewer      — RealVNC removed the pinned dmg upstream (404)
#   tigervnc        — SourceForge downloads are proxy-blocked (403)
#   blackhole-2ch   — needs a sudo pkg installer; install by hand when needed
#
# App casks need an admin password on this machine (/Applications is root:admin),
# so drawio, kdiff3 and turbovnc-viewer only install from an interactive shell.
cask "android-platform-tools"
cask "calibre"
cask "docker-desktop"
cask "drawio"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "inkscape"
cask "iterm2"
cask "kdiff3"
# cask "meld" — on hold: cdn download is blocked by the corporate proxy (403).
# kdiff3 covers diffing/merging in the meantime.
cask "notunes"
cask "libreoffice"
cask "turbovnc-viewer"
cask "visual-studio-code"
vscode "42crunch.vscode-openapi"
vscode "bierner.markdown-mermaid"
vscode "factory.factory-vscode-extension"
vscode "fwcd.kotlin"
# github.copilot-chat is bundled with VS Code itself now: the CLI reports it as
# already installed but never lists it, so declaring it is permanent false drift.
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "hashicorp.terraform"
vscode "jebbs.plantuml"
vscode "mathiasfrohlich.kotlin"
vscode "mechatroner.rainbow-csv"
vscode "miragon-gmbh.vs-code-bpmn-modeler"
vscode "ms-azure-devops.azure-pipelines"
vscode "ms-azuretools.vscode-azure-github-copilot"
vscode "ms-azuretools.vscode-azure-mcp-server"
vscode "ms-azuretools.vscode-azurefunctions"
vscode "ms-azuretools.vscode-azureresourcegroups"
vscode "ms-azuretools.vscode-azureterraform"
vscode "ms-azuretools.vscode-bicep"
vscode "ms-azuretools.vscode-containers"
vscode "ms-dotnettools.csdevkit"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.powershell"
vscode "redhat.java"
vscode "redhat.vscode-yaml"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vstirbu.vscode-mermaid-preview"
vscode "tomoki1207.pdf"
vscode "anthropic.claude-code"
